type PromptMechanics = { id: string; kind: 'prompt' | 'special' }
type RuleMechanics = {
  id: string
  kind: 'temporary-rule'
  target: 'current-player' | 'everyone' | 'choose-player'
  duration: { amount: number; unit: 'turns' | 'circles' }
}

export const cardMechanics: readonly (PromptMechanics | RuleMechanics)[] = [
  { id: 'three-word-day', kind: 'prompt' },
  { id: 'tiny-sales-pitch', kind: 'prompt' },
  { id: 'unpopular-snack', kind: 'prompt' },
  { id: 'soundtrack', kind: 'prompt' },
  { id: 'bad-superpower', kind: 'prompt' },
  { id: 'two-second-logo', kind: 'prompt' },
  { id: 'imaginary-holiday', kind: 'prompt' },
  { id: 'table-awards', kind: 'prompt' },
  { id: 'odd-one-out', kind: 'prompt' },
  { id: 'five-things', kind: 'prompt' },
  { id: 'backwards-introduction', kind: 'prompt' },
  { id: 'mystery-object', kind: 'prompt' },
  { id: 'group-photo-title', kind: 'prompt' },
  { id: 'tiny-debate', kind: 'prompt' },
  { id: 'holiday-planner', kind: 'prompt' },
  { id: 'silent-movie', kind: 'prompt' },
  { id: 'table-telepathy', kind: 'prompt' },
  { id: 'museum-piece', kind: 'prompt' },
  { id: 'new-constellation', kind: 'prompt' },
  { id: 'restaurant-review', kind: 'prompt' },
  { id: 'animal-interview', kind: 'prompt' },
  { id: 'one-word-story', kind: 'prompt' },
  { id: 'terrible-invention', kind: 'prompt' },
  { id: 'time-traveller', kind: 'prompt' },
  { id: 'fake-fact', kind: 'prompt' },
  { id: 'perfect-pair', kind: 'prompt' },
  { id: 'mini-mime', kind: 'prompt' },
  { id: 'opening-credits', kind: 'prompt' },
  { id: 'weather-report', kind: 'prompt' },
  { id: 'first-impression', kind: 'prompt' },
  { id: 'rhythm-copy', kind: 'prompt' },
  { id: 'shared-toast', kind: 'prompt' },
  {
    id: 'royal-requests',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'third-person',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'news-anchor',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'question-time',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'invisible-microphone',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'dramatic-pause',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'round-of-applause',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'imaginary-hat',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  { id: 'last-call', kind: 'special' },
  { id: 'captains-choice', kind: 'special' },
  { id: 'pocket-tradition', kind: 'prompt' },
  { id: 'childhood-invention', kind: 'prompt' },
  { id: 'tiny-victory', kind: 'prompt' },
  { id: 'unexpected-expert', kind: 'prompt' },
  { id: 'future-postcard', kind: 'prompt' },
  { id: 'sound-of-home', kind: 'prompt' },
  { id: 'borrowed-skill', kind: 'prompt' },
  { id: 'perfect-break', kind: 'prompt' },
  { id: 'umbrella-election', kind: 'prompt' },
  { id: 'fictional-mayor', kind: 'prompt' },
  { id: 'breakfast-border', kind: 'prompt' },
  { id: 'robot-pet', kind: 'prompt' },
  { id: 'weekend-vote', kind: 'prompt' },
  { id: 'new-colour', kind: 'prompt' },
  { id: 'team-mascot', kind: 'prompt' },
  { id: 'small-luxury', kind: 'prompt' },
  { id: 'last-letter-link', kind: 'prompt' },
  { id: 'forbidden-vowel', kind: 'prompt' },
  { id: 'compound-switch', kind: 'prompt' },
  { id: 'alliterative-alias', kind: 'prompt' },
  { id: 'two-word-review', kind: 'prompt' },
  { id: 'rhyme-ladder', kind: 'prompt' },
  { id: 'acronym-agency', kind: 'prompt' },
  { id: 'one-letter-upgrade', kind: 'prompt' },
  { id: 'colour-menu', kind: 'prompt' },
  { id: 'things-with-wheels', kind: 'prompt' },
  { id: 'night-sounds', kind: 'prompt' },
  { id: 'fictional-places', kind: 'prompt' },
  { id: 'three-pocket-things', kind: 'prompt' },
  { id: 'weather-verbs', kind: 'prompt' },
  { id: 'no-kitchen-tools', kind: 'prompt' },
  { id: 'round-things', kind: 'prompt' },
  { id: 'shopping-chain', kind: 'prompt' },
  { id: 'gesture-recall', kind: 'prompt' },
  { id: 'three-object-glance', kind: 'prompt' },
  { id: 'name-rewind', kind: 'prompt' },
  { id: 'story-detail', kind: 'prompt' },
  { id: 'silent-sequence', kind: 'prompt' },
  { id: 'menu-memory', kind: 'prompt' },
  { id: 'first-word-return', kind: 'prompt' },
  { id: 'shared-count', kind: 'prompt' },
  { id: 'mirror-hands', kind: 'prompt' },
  { id: 'same-shape', kind: 'prompt' },
  { id: 'alphabet-duet', kind: 'prompt' },
  { id: 'clap-gap', kind: 'prompt' },
  { id: 'countdown-pair', kind: 'prompt' },
  { id: 'shared-drawing', kind: 'prompt' },
  { id: 'alternating-introductions', kind: 'prompt' },
  { id: 'customer-service', kind: 'prompt' },
  { id: 'slow-motion-goal', kind: 'prompt' },
  { id: 'object-monologue', kind: 'prompt' },
  { id: 'whisper-trailer', kind: 'prompt' },
  { id: 'royal-announcement', kind: 'prompt' },
  { id: 'sports-commentary', kind: 'prompt' },
  { id: 'voice-switch', kind: 'prompt' },
  { id: 'pantomime-machine', kind: 'prompt' },
  { id: 'cloud-job', kind: 'prompt' },
  { id: 'tiny-dragon', kind: 'prompt' },
  { id: 'time-capsule-label', kind: 'prompt' },
  { id: 'moon-shop', kind: 'prompt' },
  { id: 'backwards-zoo', kind: 'prompt' },
  { id: 'helpful-ghost', kind: 'prompt' },
  { id: 'weather-subscription', kind: 'prompt' },
  { id: 'miniature-city', kind: 'prompt' },
  { id: 'sandwich-constitution', kind: 'prompt' },
  { id: 'snack-sound-effects', kind: 'prompt' },
  { id: 'menu-translation', kind: 'prompt' },
  { id: 'flavour-invention', kind: 'prompt' },
  { id: 'picnic-problem', kind: 'prompt' },
  { id: 'last-biscuit', kind: 'prompt' },
  { id: 'soup-advert', kind: 'prompt' },
  { id: 'midnight-menu', kind: 'prompt' },
  { id: 'wrong-guidebook', kind: 'prompt' },
  { id: 'suitcase-limits', kind: 'prompt' },
  { id: 'station-announcement', kind: 'prompt' },
  { id: 'island-government', kind: 'prompt' },
  { id: 'postcard-mixup', kind: 'prompt' },
  { id: 'tourist-statue', kind: 'prompt' },
  { id: 'hotel-review', kind: 'prompt' },
  { id: 'travel-initials', kind: 'prompt' },
  { id: 'song-without-song', kind: 'prompt' },
  { id: 'doorbell-composer', kind: 'prompt' },
  { id: 'beat-name', kind: 'prompt' },
  { id: 'soundtrack-switch', kind: 'prompt' },
  { id: 'fictional-band', kind: 'prompt' },
  { id: 'tiny-jingle', kind: 'prompt' },
  { id: 'volume-detective', kind: 'prompt' },
  { id: 'percussion-pass', kind: 'prompt' },
  { id: 'plot-in-reverse', kind: 'prompt' },
  { id: 'sequel-title', kind: 'prompt' },
  { id: 'background-actor', kind: 'prompt' },
  { id: 'book-cover', kind: 'prompt' },
  { id: 'three-genre-story', kind: 'prompt' },
  { id: 'movie-prop', kind: 'prompt' },
  { id: 'ending-vote', kind: 'prompt' },
  { id: 'trailer-voiceover', kind: 'prompt' },
  { id: 'unsung-helper', kind: 'prompt' },
  { id: 'compliment-metaphor', kind: 'prompt' },
  { id: 'team-superpower', kind: 'prompt' },
  { id: 'good-news-bulletin', kind: 'prompt' },
  { id: 'future-award', kind: 'prompt' },
  { id: 'kindness-chain', kind: 'prompt' },
  { id: 'shared-project', kind: 'prompt' },
  { id: 'celebration-budget', kind: 'prompt' },
  { id: 'opposite-advice', kind: 'prompt' },
  { id: 'explain-without-hands', kind: 'prompt' },
  { id: 'object-alibi', kind: 'prompt' },
  { id: 'odd-instruction', kind: 'prompt' },
  { id: 'size-order', kind: 'prompt' },
  { id: 'false-choice', kind: 'prompt' },
  { id: 'question-detective', kind: 'prompt' },
  { id: 'ridiculous-proof', kind: 'prompt' },
  { id: 'secret-season', kind: 'prompt' },
  { id: 'number-agreement', kind: 'prompt' },
  { id: 'predict-the-snack', kind: 'prompt' },
  { id: 'colour-consensus', kind: 'prompt' },
  { id: 'fictional-roommate', kind: 'prompt' },
  { id: 'choose-the-ending', kind: 'prompt' },
  { id: 'weekend-object', kind: 'prompt' },
  { id: 'secret-hand', kind: 'prompt' },
  { id: 'nearest-match', kind: 'prompt' },
  { id: 'table-map', kind: 'prompt' },
  { id: 'object-election', kind: 'prompt' },
  { id: 'left-right-check', kind: 'prompt' },
  { id: 'caption-contest', kind: 'prompt' },
  { id: 'common-ground', kind: 'prompt' },
  { id: 'room-riddle', kind: 'prompt' },
  { id: 'farewell-speech', kind: 'prompt' },
  {
    id: 'radio-signoff',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'proper-introductions',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'no-yes-no',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'weather-comparison',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'phantom-notebook',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'finger-curtain',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'polite-correction',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'question-echo',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'name-free-chat',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'mini-bow',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'robot-punctuation',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'word-of-the-round',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'future-tense',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'thanks-to-the-table',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'pretend-doorbell',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'number-as-words',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'curious-expert',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'no-pointing',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'fictional-assistant',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'soft-fanfare',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'compliment-receipt',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'royal-we',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'handmade-quotation',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'left-hand-wave',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'sporting-answer',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'imaginary-spectacles',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'proper-food-title',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'thoughtful-chin',
    kind: 'temporary-rule',
    target: 'current-player',
    duration: { amount: 3, unit: 'turns' },
  },
  {
    id: 'sound-effect-agreement',
    kind: 'temporary-rule',
    target: 'choose-player',
    duration: { amount: 1, unit: 'circles' },
  },
  {
    id: 'tiny-round-table',
    kind: 'temporary-rule',
    target: 'everyone',
    duration: { amount: 1, unit: 'circles' },
  },
]
